# DeployMind Configuration Example
# Copy this file to .deploymind.yml and customize for your needs

# Default settings (used when no profile is specified)
defaults:
  repository: your-org/your-app
  instance: i-1234567890abcdef0
  port: 8080
  strategy: rolling
  environment: production

# Deployment profiles for different environments
profiles:
  # Development environment
  dev:
    repository: your-org/your-app
    instance: i-dev123456789
    port: 3000
    environment: development
    region: us-west-2
    health_check_path: /health
    strategy: rolling

  # Staging environment
  staging:
    repository: your-org/your-app
    instance: i-staging987654
    port: 4000
    environment: staging
    region: us-east-1
    strategy: blue-green

  # Production environment
  prod:
    repository: your-org/your-app
    instance: i-prod111222333
    port: 8080
    environment: production
    region: us-east-1
    strategy: rolling
    extra:
      alert_on_failure: true
      slack_webhook: https://hooks.slack.com/...

# Retry configuration
retry:
  max_retries: 3
  delay_seconds: 5
  exponential_backoff: true

# Timeout configuration (in seconds)
timeouts:
  health_check: 120  # 2 minutes
  build: 600         # 10 minutes
  deployment: 300    # 5 minutes

# Performance settings
performance:
  enable_caching: true
  cache_ttl_seconds: 300  # 5 minutes

# Logging configuration
logging:
  level: INFO  # DEBUG, INFO, WARNING, ERROR
  verbose: false
